//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DinJobPortalEntities : DbContext
    {
        public DinJobPortalEntities()
            : base("name=DinJobPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_employee_registration_data> tb_employee_registration_data { get; set; }
        public virtual DbSet<tb_employer_registration_data> tb_employer_registration_data { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_exception> tb_exception { get; set; }
        public virtual DbSet<tb_verification_code> tb_verification_code { get; set; }
        public virtual DbSet<tb_master_masters> tb_master_masters { get; set; }
    }
}
