//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DinJobPortalEntities : DbContext
    {
        public DinJobPortalEntities()
            : base("name=DinJobPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_education_employee> tb_education_employee { get; set; }
        public virtual DbSet<tb_employee_registration_data> tb_employee_registration_data { get; set; }
        public virtual DbSet<tb_employer_registration_data> tb_employer_registration_data { get; set; }
        public virtual DbSet<tb_exception> tb_exception { get; set; }
        public virtual DbSet<tb_experience_employee> tb_experience_employee { get; set; }
        public virtual DbSet<tb_external_url_employee> tb_external_url_employee { get; set; }
        public virtual DbSet<tb_languages_employee> tb_languages_employee { get; set; }
        public virtual DbSet<tb_master_masters> tb_master_masters { get; set; }
        public virtual DbSet<tb_profile_employee> tb_profile_employee { get; set; }
        public virtual DbSet<tb_projects_employee> tb_projects_employee { get; set; }
        public virtual DbSet<tb_skills_employee> tb_skills_employee { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_profile_employer> tb_profile_employer { get; set; }
        public virtual DbSet<tb_department_employer> tb_department_employer { get; set; }
        public virtual DbSet<tb_jobs> tb_jobs { get; set; }
        public virtual DbSet<tb_apply_job> tb_apply_job { get; set; }
        public virtual DbSet<tb_cvs_employee> tb_cvs_employee { get; set; }
    }
}
