//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_apply_job
    {
        public int id { get; set; }
        public int profile_id { get; set; }
        public int job_id { get; set; }
        public string expected_salary { get; set; }
        public string cover_letter { get; set; }
        public Nullable<bool> is_employee_currently_working { get; set; }
        public string last_company_name { get; set; }
        public string work_duration { get; set; }
        public Nullable<System.DateTime> availability { get; set; }
        public int cv_id { get; set; }
        public string employer_comment { get; set; }
        public Nullable<int> employer_rating { get; set; }
        public string application_status { get; set; }
        public Nullable<System.DateTime> application_time { get; set; }
        public string current_salary { get; set; }
    
        public virtual tb_cvs_employee tb_cvs_employee { get; set; }
        public virtual tb_jobs tb_jobs { get; set; }
        public virtual tb_profile_employee tb_profile_employee { get; set; }
    }
}
