//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cvs_employee
    {
        public tb_cvs_employee()
        {
            this.tb_apply_job = new HashSet<tb_apply_job>();
        }
    
        public int id { get; set; }
        public int profile_id { get; set; }
        public string cv_name { get; set; }
        public string cv_catagory { get; set; }
        public string cv_file_name { get; set; }
        public Nullable<bool> is_cv_hidden { get; set; }
        public Nullable<bool> is_cv_deleted { get; set; }
        public Nullable<System.DateTime> cv_upload_date { get; set; }
    
        public virtual ICollection<tb_apply_job> tb_apply_job { get; set; }
        public virtual tb_profile_employee tb_profile_employee { get; set; }
    }
}
