//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_department_employer
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> profile_id { get; set; }
        public string department_name { get; set; }
        public int no_of_employee_in_department { get; set; }
        public string department_intro { get; set; }
    
        public virtual tb_user tb_user { get; set; }
    }
}
