//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_experience_employee
    {
        public int id { get; set; }
        public int profile_id { get; set; }
        public string job_title { get; set; }
        public string company_location { get; set; }
        public bool experience_currently_working { get; set; }
        public Nullable<System.DateTime> experience_start_date { get; set; }
        public Nullable<System.DateTime> experience_end_date { get; set; }
        public string experience_notes { get; set; }
        public string company_name { get; set; }
    
        public virtual tb_profile_employee tb_profile_employee { get; set; }
    }
}
