//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class tb_profile_employer
    {
        public tb_profile_employer()
        {
            this.tb_department_employer = new HashSet<tb_department_employer>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        [Required]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                                             @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                                                @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Email is not valid")]
        public string email { get; set; }
        public System.DateTime company_establishment_date { get; set; }
        public string profile_picture { get; set; }
        public string cover_picture { get; set; }
        public string video_id { get; set; }
        [Required]
        [AllowHtml]
        [RegularExpression(@"^(?![\W_]+$)(?!\d+$)[a-zA-Z0-9 .&',_-]+$", ErrorMessage = "Summary must contain atleast 1 Alphabets")]
        public string summary { get; set; }
        [Required]
        [AllowHtml]
        [RegularExpression(@"^(?![\W_]+$)(?!\d+$)[a-zA-Z0-9 .&',_-]+$", ErrorMessage = "Comapny Location must contain atleast 1 Alphabets")]
        public string company_location { get; set; }
        public Nullable<int> no_of_employees { get; set; }
    
        public virtual tb_user tb_user { get; set; }
        public virtual ICollection<tb_department_employer> tb_department_employer { get; set; }
    }
}
