//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_profile_employer
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string email { get; set; }
        public System.DateTime company_establishment_date { get; set; }
        public string profile_picture { get; set; }
        public string cover_picture { get; set; }
        public string video_id { get; set; }
        public string summary { get; set; }
    
        public virtual tb_user tb_user { get; set; }
    }
}
