//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_user
    {
        public tb_user()
        {
            this.tb_employee_registration_data = new HashSet<tb_employee_registration_data>();
            this.tb_employer_registration_data = new HashSet<tb_employer_registration_data>();
        }
    
        public int id { get; set; }
        [Required]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                                             @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                                                @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Email is not valid")]
        public string email { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [StringLength(256, ErrorMessage = "Must be between 6 and 32 characters", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required]
        public string user_type { get; set; }
        public bool is_active { get; set; }
        public bool is_verified { get; set; }
        public string last_change_password { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual ICollection<tb_employee_registration_data> tb_employee_registration_data { get; set; }
        public virtual ICollection<tb_employer_registration_data> tb_employer_registration_data { get; set; }
    }
}
