//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Din_Media_Group_Job_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public tb_user()
        {
            this.tb_employee_registration_data = new HashSet<tb_employee_registration_data>();
            this.tb_employer_registration_data = new HashSet<tb_employer_registration_data>();
            this.tb_profile_employee = new HashSet<tb_profile_employee>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public bool is_active { get; set; }
        public bool is_verified { get; set; }
        public string last_change_password { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual ICollection<tb_employee_registration_data> tb_employee_registration_data { get; set; }
        public virtual ICollection<tb_employer_registration_data> tb_employer_registration_data { get; set; }
        public virtual ICollection<tb_profile_employee> tb_profile_employee { get; set; }
    }
}
